### ISSUE TITLE
Use MCProtocolLib

### ISSUE THREAD

**Issue by phase** [rbrick/MCGet#1]
Judging from the very detailed description in the README, I gathered that this project has something to do with Minecraft Packets. I'd suggest using [MCProtocolLib](https://github.com/Steveice10/MCProtocolLib) instead of making your own, as it has already been made.

**Comment by rbrick** [comment]
@phase Thank you for the suggestion. The person who I am working with on this, is not wanting to use any third party libraries (to make it "lightweight"), I'd much rather use a framework or library (Such as Netty (Already have something similar written using Netty), or as stated MCProtocolLib).
